version: "3.6"

services:
  sut:
    build: .
    volumes:
      - deluge_config:/config
    command: >
      bash -c "/usr/local/bin/start.sh &
               /usr/local/bin/test.sh -t 30 -u http://localhost:8112/ -e Deluge"

volumes:
  deluge_config:
    driver_opts:
      type: tmpfs
      device: tmpfs
