version: '3.6'

services:
  sut:
    image: damiantroy/deluge:${CACHE_TAG}
    volumes:
      - /config
    networks:
      - default_network
    depends_on:
      - deluge
    command: /usr/local/bin/test.sh -t 60 -u http://deluge:8112 -e Deluge

  deluge:
    image: damiantroy/deluge:${CACHE_TAG}
    volumes:
      - /config
    networks:
      - default_network
    ports:
      - "8112:8112"

networks:
  default_network:
    driver: bridge

