version: "3.6"

services:
  sut:
    image: damiantroy/deluge:${CACHE_TAG}
    volumes:
      - deluge_config:/config
    command: >
      bash -c "/usr/local/bin/start.sh &
               /usr/local/bin/test.sh -t 60 -u http://deluge:8112 -e Deluge"

volumes:
  deluge_config:
    driver_opts:
      type: tmpfs
      device: tmpfs
